name: Makefile CI

on:
  push:
    branches: [ "abm-0.3" ]
  pull_request:
    branches: [ "abm-0.3" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: Install dependencies
      run: sudo apt install gcc-arm-none-eabi python3 device-tree-compiler libfdt-dev
  
    - name: make
      run: make TOOLCHAIN_PREFIX=arm-none-eabi- msm8937-secondary


    - name: Run distcheck
      run: make distcheck
